version: "3.5"

networks:
  eth-testnet:
    external: true
    name: eth-docker-testnet

services:
  validator-solo:
    image: hyperledger/besu:latest
    container_name: validator-solo
    environment:
      - BESU_CONFIG=/home/besu/config/config.toml
      - BESU_DATA_PATH=/home/besu/data
    networks:
      - eth-testnet
    expose:
      - 8545
      - 8546
      - 30303
      - 30303/udp
    ports:
      - 28540:8545
#      - ${LOCAL_RPC_HTTP__PORT}:8545
#      - ${LOCAL_RPC_WS_PORT}:8546
#      - ${LOCAL_P2P_PORT}:30303
    volumes:
      - ${LOCAL_DEPLOY_PATH}:/home/besu
    tty: true
    entrypoint: bash
