version: "3.5"

networks:
  eth_private_testnet:
    name: ${TESTNET_NAME:-eth_docker_testnet}
    external: true

services:

  besu-validator-1:
    image: hyperledger/besu:latest
    container_name: besu-validator-1
    environment:
      - BESU_CONFIG:/home/besu/config/config.toml
      - BESU_DATA_PATH:/home/besu/data
    networks:
      - eth-testnet
    expose:
      - 8545
      - 8546
      - 30303
      - 30303/udp
#    ports:
#      - ${LOCAL_RPC_HTTP__PORT}:8545
#      - ${LOCAL_RPC_WS_PORT}:8546
#      - ${LOCAL_P2P_PORT}:30303
    volumes:
      - ./deployment-test//besu-validator-1:/home/besu
      
  besu-validator-0:
    image: hyperledger/besu:latest
    container_name: besu-validator-0
    environment:
      - BESU_CONFIG:/home/besu/config/config.toml
      - BESU_DATA_PATH:/home/besu/data
    networks:
      - eth-testnet
    expose:
      - 8545
      - 8546
      - 30303
      - 30303/udp
#    ports:
#      - ${LOCAL_RPC_HTTP__PORT}:8545
#      - ${LOCAL_RPC_WS_PORT}:8546
#      - ${LOCAL_P2P_PORT}:30303
    volumes:
      - ./deployment-test//besu-validator-0:/home/besu
      
